### PR TITLE
support for hot module reload

### PR DESCRIPTION
**Pull request by AEPKILL**

### CODE REVIEW

**Comment by jalkoby** [comment]
It doesn't look like "hot module reload". please look at the idea of it https://webpack.js.org/concepts/hot-module-replacement/ . Basically HMR in our case will be updating stylesheets without "full page reload". Your changes is an another implementation what's done at the moment. So I'm sorry to say but these changes I'll reject.

Ps after all thank you for your work

**Comment by AEPKILL** [comment]
It's ok, but I need this feature, so I'll create a new project base on  `sass-webpack-plugin` if you don't mind。

**Comment by jalkoby** [comment]
up to you, it's a MIT license - you can do everything you want. 
btw I still don't get what your code changes in functionality

**Comment by AepKill** [comment]
`sass-webpack-plugin` only compile  scss/sass files once on first build , 
i want it watch scss/sass files change and continuous compile.

**Pull request closed without merging**
